os: linux
dist: bionic
language: shell

env:
  DOCKER_USERNAME: sineverba
  DOCKER_IMAGE: cfhookbash

before_install:
  - echo "before install"

install:
  - echo "install"

script:
  - echo "script"

after_success:
  - echo "after success"
