os: linux
dist: bionic
language: shell

env:
  DOCKER_USERNAME: sineverba
  DOCKER_IMAGE: cfhookbash

before_install:
  - export VCS_REF=$(git rev-parse --short HEAD)

install:
  - echo "install"

script:
  - echo "script"

after_success:
  - echo "after success"
